# Generated by Django 2.0.4 on 2018-05-08 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20180508_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='username',
            new_name='User_id',
        ),
    ]
