# Generated by Django 2.0.4 on 2018-05-09 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20180508_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='User_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_detail', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
