# Generated by Django 2.0.3 on 2018-04-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='Service_Image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
