# Generated by Django 2.0.3 on 2018-04-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20180411_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='Service_Image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
