# Generated by Django 2.0.3 on 2018-04-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20180411_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='Service_Image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
