# Generated by Django 2.0.3 on 2018-04-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20180411_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='Service_Image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
